# Generated by Django 5.1 on 2024-08-30 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_destinatario', models.CharField(max_length=100)),
                ('apellido_destinatario', models.CharField(max_length=100)),
                ('telefono_destinatario', models.CharField(max_length=20)),
                ('email_destinatario', models.EmailField(max_length=254)),
                ('direccion_entrega', models.CharField(max_length=200)),
                ('ciudad_entrega', models.CharField(max_length=100)),
                ('provincia_entrega', models.CharField(max_length=100)),
                ('codigo_postal_entrega', models.CharField(max_length=20)),
                ('estado', models.CharField(choices=[('Creado', 'Creado'), ('Recibido', 'Recibido'), ('En camino', 'En camino'), ('Entregado', 'Entregado')], default='Creado', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario')),
                ('razon_social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
        ),
    ]
